set PATH so the app can be found in /usr/local/bin at boot
/usr/local/bin isn't in the PATH by default at boot and this avoids an
error: start-stop-daemon: unable to stat
/var/squadron/--make-pidfile (No such file or directory)